version: '3'

services:
  app:
    container_name: 'Frontend_dump'
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=4002
    ports:
      #prod
      - "8096:4002"
      #dev
      # - "9104:4002"
    # command: npm install cookie-parser && npm start
    networks:
      - backend_network
    command: ["serve", '-s', "build"]

networks:
  backend_network:
    driver: bridge
