version: '3'

services:
  app:
    container_name: 'Frontend_dump'
    build: 
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/app
    #   - node_modules:/app/node_modules
    environment:
      - PORT=4002
    ports:
      - "9104:4002"
    # command: npm install cookie-parser && npm start
    networks:
      - backend_network


networks:
  backend_network:
    driver: bridge
